/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ims;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.lang.*;

/**
 *
 * @author Lucky
 */
public class NewTransaction extends javax.swing.JFrame {

    /**
     * Creates new form NewTransaction
     */
    //all transaction variables
         int type;
         int month,year,date;//case 1,case 3
         int quantity;
         float price,wprice;
         int itemId;
         int clientId;
         String cName;
         int invoice_grin;
        static int tId;
        int k;
        
        //Getting produced books from manu case1
        int book_amount;
        int left_book_amount;
       /* DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
JFormattedTextField1 txtDate = new JFormattedTextField(df);*/
      //  float left_pay_amount1;
       // int recitNo;
        
        //issing papers to manu case 3
        int no_of_ordered_books;
        int pages;
        //float left_pay_amount2;
        
        //new ruling order case 4
        String rule_type;
     //   String due_date1;
       // float left_pay_amount3;
        
       
    public NewTransaction() {
        initComponents();
        jTextField3.setVisible(false);   
        jTextField4.setVisible(false);
    //    jTextField5.setVisible(false);
      //  jTextField7.setVisible(false);
        jComboBox5.setVisible(false);
         jComboBox6.setVisible(false);
          jComboBox7.setVisible(false);
        jPanel2.setVisible(false);
     //  invoice_grin=Integer.parseInt(jTextField8.getText());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("New Transaction");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("*Type");

        jLabel3.setText("*Quantity(No. of Rims)");

        jLabel4.setText("Price(per rim)");

        jLabel5.setText("*Item ID");

        jLabel6.setText("*Client ID");

        jLabel7.setText("Company Name");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Transaction Type", "Taking a finished book order from manufatures", "Buying Papers", "Issuing papers to Manufatures", "New Ruling Order", "Ruling order Submission", "Selling Books", "Selling Paper", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select item", "1-bank paper", "2-dimy paper", "3-art paper", "4-art board", "5-box board", "6-ex book cover", "7-cr book cover", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "Marchl", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "year", "2018", "2019", "2020", "2021", "2022" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 9, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel13.setText("*Value (GSM value or CR value)");

        jLabel15.setText("*Invoice or grin number");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel16.setText("*Whole price");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel15)
                                            .addGap(124, 124, 124))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField1)
                                        .addComponent(jComboBox1, 0, 291, Short.MAX_VALUE)
                                        .addComponent(jTextField8)
                                        .addComponent(jTextField9)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2)
                                            .addGap(107, 107, 107)
                                            .addComponent(jButton3))))
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField5)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))))
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton3)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        type=jComboBox1.getSelectedIndex();
        switch (type)
        {
            case 3:jLabel9.setText("Issuesing Papers to Manufacteres");
                     jLabel10.setText("Number of Books ordered");
                     jLabel11.setText("Size(Number of Pages)");
                     jLabel17.setText("Due date");
                     jPanel2.setVisible(true);
                     jTextField3.setVisible(true);
                     jTextField4.setVisible(true);
                      jComboBox5.setVisible(true);
                      jComboBox6.setVisible(true);
                       jComboBox7.setVisible(true);
                     break;
            case 4:jLabel9.setText("New Ruling Order");
                     jLabel10.setText("Type of Rules");
                     jLabel17.setText("Due Date");
                     jTextField3.setVisible(true);   
                    
                     jPanel2.setVisible(true); 
                     jComboBox5.setVisible(true);
                      jComboBox6.setVisible(true);
                       jComboBox7.setVisible(true);
                     break;
            case 1:jLabel9.setText("Getting produced books from Manufacteres");
                     jLabel10.setText("Amount of Books");
                     jLabel11.setText("Amount of Books that are not submitted yet");
                     jLabel17.setText("Due dates of left book amount");
                 
                     jTextField3.setVisible(true);   
                     jTextField4.setVisible(true); 
                 
                     jPanel2.setVisible(true);
                     jComboBox5.setVisible(true);
                      jComboBox6.setVisible(true);
                       jComboBox7.setVisible(true);
                     break;
           
            default:jPanel2.setVisible(false);
        }
        
        System.out.println(type);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
         jTextField3.setText("");
        jTextField4.setText("");
         jTextField6.setText("");
        jTextField8.setText("");
         jTextField9.setText("");
         jLabel8.setText("");
        
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
      //  jComboBox3.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        //jComboBox1.set
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        try
        {   
            invoice_grin=Integer.parseInt(jTextField8.getText());
             cName=jTextField7.getText(); 
              clientId=Integer.parseInt(jTextField5.getText()); 
               itemId=jComboBox2.getSelectedIndex(); 
                quantity=Integer.parseInt(jTextField1.getText());
                price=Float.parseFloat(jTextField2.getText());
                 wprice=Float.parseFloat(jTextField9.getText());
            //Loading driver
              Class.forName("com.mysql.jdbc.Driver");

            //creating connectio
              Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/imsreal","root","lucky");
       
              Statement s = con.createStatement();	//creating statement
              
             if((jComboBox1.getSelectedIndex()==0)||(jComboBox2.getSelectedIndex()==0)||(jTextField5.getText().equals(""))||jTextField7.getText().equals("")||(jTextField8.getText().equals(""))||(jTextField1.getText().equals(""))||(jTextField2.getText().equals("")||(jTextField6.getText().equals(""))||(jTextField9.getText().equals(""))))
                {jLabel8.setText("Enter All * Information please!!");}
              
              else
              {
                 // jLabel8.setText("Successfully added transaction");
                  ResultSet r =s.executeQuery("select max(tId) from transact ");
              // group by tId maybe  
             r.next();// result set contains sql result database , next method moves the cursor to next line
              k=r.getInt(1);//get the integer in tId column
                 
              k++;
              tId=k;
                  System.out.println("tId"+tId);
             
               switch(type)
              {
                  case 1:book_amount=Integer.parseInt(jTextField3.getText());
                      left_book_amount=Integer.parseInt(jTextField4.getText());
                      invoice_grin=Integer.parseInt(jTextField8.getText());
                     
                      year=jComboBox6.getSelectedIndex();
                    
                      month=jComboBox5.getSelectedIndex();
                      date=jComboBox7.getSelectedIndex();
                     if((jTextField3.getText().equals(""))||(jTextField4.getText().equals(""))||(jTextField8.getText().equals(""))||(jComboBox5.getSelectedIndex()==0)||(jComboBox6.getSelectedIndex()==0)||(jComboBox7.getSelectedIndex()==0))
                       {jLabel8.setText("Enter All * Information!!");}
                        
                      else
                      {
                          s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                          s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                          s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
                          s.executeUpdate("insert into acceptingfrommanu(tId,amount,leftAmount,year,month,date) value ('"+tId+"','"+book_amount+"','"+left_book_amount+"','"+year+"','"+month+"','"+date+"')");
                          s.executeUpdate("insert into preforms(nationalId,tId) values ('"+clientId+"','"+tId+"')");
                          jLabel8.setText("Successfully added transaction oh ye!");}
                      break;
                  case 2:
                        s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                        s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                        s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
                        s.executeUpdate("insert into buyingpaper(tId) value('"+tId+"')");
                         s.executeUpdate("insert into preforms(nationalId,tId) values ('"+clientId+"','"+tId+"')");
                        jLabel8.setText("Successfully added transaction oh ye!");
                      break;
                  case 3:no_of_ordered_books=Integer.parseInt(jTextField3.getText());
                        
                       pages=Integer.parseInt(jTextField4.getText());
                     
                       year=jComboBox6.getSelectedIndex();
                       month=jComboBox5.getSelectedIndex();
                       date=jComboBox7.getSelectedIndex();
                      
                       if((jTextField3.getText().equals(""))||(jTextField4.getText().equals(""))||(jTextField8.getText().equals(""))||(jComboBox5.getSelectedIndex()==0)||(jComboBox6.getSelectedIndex()==0)||(jComboBox7.getSelectedIndex()==0))
                       {jLabel8.setText("Enter All * Information!!");}
                       else
                      {s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                       s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                       s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
                    
                       s.executeUpdate("insert into issuingtomanu(tId,year,month,date) value ('"+tId+"','"+year+"','"+month+"','"+date+"')");
                       s.executeUpdate("insert into issuingtomanuno(tId,noOfBooks) values('"+tId+"','"+no_of_ordered_books+"')");
                       s.executeUpdate("insert into issuingtomanupages(tId,pages) values('"+tId+"','"+pages+"')");
                        s.executeUpdate("insert into preforms(nationalId,tId) values ('"+clientId+"','"+tId+"')");
                       jLabel8.setText("Successfully added transaction oh ye!");}
                      break;
                  case 4:rule_type=jTextField3.getText();
                       year=jComboBox6.getSelectedIndex();
                       month=jComboBox5.getSelectedIndex();
                       date=jComboBox7.getSelectedIndex();
                      
                       if((jTextField3.getText().equals(""))||(jTextField4.getText().equals(""))||(jTextField8.getText().equals(""))||(jComboBox5.getSelectedIndex()==0)||(jComboBox6.getSelectedIndex()==0)||(jComboBox7.getSelectedIndex()==0))
                       {jLabel8.setText("Enter All * Information!!");}
                       
                       else
                      {s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                       s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                       s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
             
                       s.executeUpdate("insert into rulingorder(tId,year,month,date) value ('"+tId+"','"+year+"','"+month+"','"+date+"')");
                       s.executeUpdate("insert into rulingordertype(tId,ruleType) value ('"+tId+"','"+rule_type+"')");
                        s.executeUpdate("insert into preforms(nationalId,tId) values ('"+clientId+"','"+tId+"')");
                       jLabel8.setText("Successfully added transaction oh ye!");}
                      break;
                  case 5:
                       s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                       s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                       s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
                      
                       s.executeUpdate("insert into rulingordersubmission(tId) value('"+tId+"')");
                        s.executeUpdate("insert into preforms(nationalId,tId) values ('"+clientId+"','"+tId+"')");
                       jLabel8.setText("Successfully added transaction oh ye!");
                      break;
                  case 6:
                       s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                       s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                       s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
                      
                       s.executeUpdate("insert into sellingbooks(tId) value('"+tId+"')");
                        s.executeUpdate("insert into preforms(nationalId,tId) values ('"+clientId+"','"+tId+"')");
                       jLabel8.setText("Successfully added transaction oh ye!");
                      break;
                  case 7:
                       s.executeUpdate("insert into transact(tId,invoice_or_g_no) value ('"+tId+"','"+invoice_grin+"')");
                       s.executeUpdate("insert into involves(tId,iId,pricePerRim,wholePrice) value('"+tId+"','"+itemId+"','"+price+"','"+wprice+"')");
                       s.executeUpdate("insert into involvesquantity(tId,iId,quantity) values ('"+tId+"','"+itemId+"','"+quantity+"')");
                      
                       s.executeUpdate("insert into sellingpaper(tId) value('"+tId+"')");
                        s.executeUpdate("insert into preforms(nationalId,tId values ('"+clientId+"','"+tId+"'))");
                       jLabel8.setText("Successfully added transaction oh ye!");
                      break;
              
             // s.executeUpdate(price);
              }
              }
             //  s.executeUpdate("INSERT INTO `time_entry`(pid,tid,rid,tspend,description) VALUE ('"+pid+"','"+tid+"','"+rid+"',"+tspent+",'"+des+"')");
               con.close();	//closing connection
         }

        catch(Exception e)
        {
              {jLabel8.setText("Error!!");}
            System.out.println(e);
            
        }  
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      // quantity=(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
           // itemId=String.valueOf(jComboBox2.getSelectedItem());        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
     //   invoice_grin=Integer.parseInt(jTextField8.getText());
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                        this.dispose(); 
                       imsServicesUI n1=new imsServicesUI();
                       n1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
      // jTextField3.setVisible(false); 
     //   System.out.println("cName:"+cName);
      //  invoice_grin=Integer.parseInt(jTextField8.getText());
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
              new NewTransaction().setVisible(true);
               //  jTextField3.setVisible(false); 
              //invoice_grin=Integer.parseInt(jTextField8.getText());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
